### ISSUE TITLE
to_shp method does not pass options hash

### ISSUE THREAD

**Issue by slorek** [scooterw/ffi-ogr#14]
The `OGR::DataSource#to_shp` method does not pass the options hash when it calls `to_format`. I worked around this by using `to_format` directly for now.

**Comment by scooterw** [comment]
Sorry about that! I will take a look this afternoon. I am glad you were able to find a workaround in the meantime. Thanks for using this!

**Comment by slorek** [comment]
No, thank you for the useful library!

**Comment by scooterw** [comment]
This should be fixed with 94d8f70. I tested by passing {shpt: 'null'} with to_shp, and got the expected .dbf without the .shp and other files. Please let me know whether this fixes your issue. Thanks!

**Comment by slorek** [comment]
This fixes it, thanks!
