### ISSUE TITLE
Could not load GDAL library 

### ISSUE THREAD

**Issue by ronanduddy** [scooterw/ffi-ogr#16]
Hi there, 

I get an error when trying to run the rails server with ffi-ogr:

/home/ronan/.rvm/gems/ruby-2.3.0/gems/ffi-ogr-0.1.0/lib/ffi-ogr.rb:324:in `rescue in <module:FFIOGR>': Could not load GDAL library (LoadError)

Would this be related to gdal removing ruby bindings?: https://trac.osgeo.org/gdal/wiki/GdalOgrInRuby

Thanks, 
Ronan

**Comment by blackrez** [comment]
Hello,



I don't think this is related because the bindings removed use swig and
this one use ffi.




--

  Nabil Servais

  nabil@eml.cc







Le Mar 31 janv 2017, à 18:03, Rónán Duddy a écrit :

> Hi there,



> I get an error when trying to run the rails server with ffi-ogr:



> /home/ronan/.rvm/gems/ruby-2.3.0/gems/ffi-ogr-0.1.0/lib/ffi-
> ogr.rb:324:in `rescue in module:FFIOGR': Could not load GDAL library
> (LoadError)
> Would this be related to gdal removing ruby bindings?:
> https://trac.osgeo.org/gdal/wiki/GdalOgrInRuby
> Thanks,

>  Ronan



> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
> 




Links:

  1. https://github.com/scooterw/ffi-ogr/issues/16

**Comment by ronanduddy** [comment]
I'll check it out my issue.. Cheers! ... I fixed it, it was a faulty installation on my part.
